# Gradle Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true

# Mod Info
modGroup = com.hirrao
modId = disablenarrator
modName = Disable Narrator
modVersion = 1.0.0

# Minecraft Info
mcVersion = 1.12.2
userName = hirrao

coreModPluginPath =
generateTokenPath =

# Shadow Configurations
useShadowDeps = false
minimizeShadowedDependencies = false
relocateShadowedDependencies = false
shadowRelocationPrefix =